name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/jobs/lint.yml

#   test:
#     needs: lint
#     uses: ./.github/workflows/jobs/test.yml

  build:
    needs: lint
    uses: ./.github/workflows/jobs/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/jobs/deploy.yml
