name: Deploy Job

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
