name: Development Workflow

on:
  push:
    branches:
      - dev

jobs:
  lint:
    uses: ./.github/workflows/jobs/lint.yml

#   test:
#     needs: lint
#     uses: ./.github/workflows/jobs/test.yml
