name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  #   test:
  #     needs: lint
  #     uses: ./.github/workflows/test.yml

  build:
    needs: lint
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
